### ISSUE TITLE
Kategorien zu einer Information

### ISSUE THREAD

**Issue by Hackyy** [Hackyy/dhbw-digitales-museum#10]
Es muss möglich sein die Informationen, die zu einer Person gehören, einer oder mehreren Kategorien zuzuweisen. Dabei handel es sich um eine N zu M Beziehung. Im Create und Edit Formular der "Informationen" muss eine List existieren wo mehrere Kategorien ausgewählt werden können.

**Comment by bennystrauch** [comment]
als dropdown oder wie hättest du es gern?

**Comment by Hackyy** [comment]
ja

**Comment by bennystrauch** [comment]
commited bitte checken.
