### ISSUE TITLE
GUI Mockup erstellen

### ISSUE THREAD

**Issue by Hackyy** [Hackyy/dhbw-digitales-museum#2]
Erstellen eines GUI Mockups zur Bedienung der Website.

**Comment by Hackyy** [comment]
Am besten ein grobes Layout überlegen. Zusätzlich ein Logo erfinden das wir auf der Seite anzeigen können.

**Comment by Alezyn** [comment]
@Hackyy Wie ist es dir lieber? Soll ich die Mockups in das Repository laden oder auf Dropbox?

**Comment by Alezyn** [comment]
Habe jetzt mal ein paar sehr einfache und an der DB orientierte Mockups erstellt. Ich glaube die Sozi-Dame hat gesagt sie wolle auch einzelne Ausstellungen aus den Personen/Informationen entwerfen. Sollte mit Frau Winter geklärt werden ob wir das in dem Umfang machen sollen, mit unserer aktuellen DB ist das ja glaube ich noch nicht umsetzbar. Insgesamt ist das Ding aber wahrscheinlich eh nicht im von der Frau erwünschten Umfang realisierbar. Zumindest nicht in unserem Rahmen.

**Comment by Hackyy** [comment]
Ok da weiß ich nun garnichts drüber mit den "einzelnen Ausstellungen". Wenn du noch weißt wie die Anforderung war, dann könntest du das in das aktuelle DB Model aufnehmen - Oder wir sprechen nochmal drüber was nun die Anforderung war.

**Comment by Hackyy** [comment]
Das Logo sieht gut aus !

**Comment by Hackyy** [comment]
@Alezyn was noch gut wäre, wenn du das Logo mit transparenten Hintergrund anlegst. Dann können wir es besser in die Applikation einbinden.

**Comment by Hackyy** [comment]
@Alezyn Wenn die Sozi-Dame einzelne Ausstellung erstellen möchte, dann sollten wir noch ein Tabelle in der DB entwerfen, wo man Personen und Informationen hinzufügen kann. Dann halte ich die Relation von Personen <=1:n=> Informationen als eine "optionale" Beziehung und man kann Informationen auch ohne eine Person erstellen.
