### ISSUE TITLE
Suche von Websiteinhalten

### ISSUE THREAD

**Issue by Hackyy** [Hackyy/dhbw-digitales-museum#25]
Es soll eine Suche geben, die es ermöglicht nach Inhalten zu suchen. Dabei sollen reine SQL-Statements verwendet werden, damit die Anforderungen vom Dozenten erfüllt sind.

**Wenn es möglich ist soll die Suche für alle Inhalte funktionieren ohne die Suche für jeden Inhaltstypen einzeln zu implementieren.**

**Comment by bennystrauch** [comment]
Suche in Personen und Information mit Ausgabe der Person

```
 Select     *
 FROM     Person, Information
 WHERE   EXISTS ( SELECT    *
                              FROM     Information, Person
                              WHERE   Person_name LIKE $request
                              OR          Person_vorname LIKE $request
                              OR          Information_titel LIKE $request
                              OR          Information_description LIKE $request)
```

**Comment by Alezyn** [comment]
Den Aufwand eine globale Suche zu implementieren halte ich bei dem Umfang unseres Projektes selbst mit Einsatz von Drittanbieter-Tools für deutlich zu groß. Mein Vorschlag wäre eventuell Google Custom Search einzubauen sobald die Seite gehostet und Testdaten eingespielt wurden, falls wir unbedingt eine globale Suche brauchen. Zusätzlich dazu würde ich in jedem Fall auf der Indexseite der Personen noch ein Suchfeld einbauen das nur Personen durchsucht und für das SQL statt dem Laravel Query Builder verwendet wird, um die Anforderung von Frau Winter zu erfüllen.

**Comment by Alezyn** [comment]
personen-suche implementiert
