### ISSUE TITLE
NotWritableException thrown by Image Controller

### ISSUE THREAD

**Issue by Alezyn** [Hackyy/dhbw-digitales-museum#36]
Beim Versuch ein Bild anzulegen kam bei mir die Fehlermeldung:

> NotWritableException in Image.php line 143:
> Can't write image data to path (C:\dev\dhbw\laravel-digitales-museum\public\uploads/information_image_1492280836.png)

OS: Windows 10; Browser: Chrome

**Comment by Hackyy** [comment]
eventuell ein Berechtigungsproblem? Ist das Verzeichnis "uploads" bei dir angelegt im Ordner "public" ?

**Comment by Alezyn** [comment]
"uploads" war nicht angelegt. Habs jetzt angelegt, jetzt kommt eine andere Fehlermeldung:

> Fehler: The image failed to upload.

Sehr aussagekräftig. Hätte jetzt vermutet es liegt daran dass der Pfad "/" und "\\" mischt.

**Comment by Alezyn** [comment]
Ok merke gerade dass der Fehler nur bei .JPG auftritt. .png geht
