### ISSUE TITLE
"Speichern/Löschen/Übernehmen" Buttons 

### ISSUE THREAD

**Issue by Hackyy** [Hackyy/dhbw-digitales-museum#47]
Anpassen der Buttons in create/delete froms für mobile Style

![image](https://cloud.githubusercontent.com/assets/9462423/25619551/9a1b894e-2f4b-11e7-99c4-34e88ca0dc50.png)

**Comment by Hackyy** [comment]
Bitte folgendes verwenden und auch Testen!
Achtung: bitte die "blod" gegenzeichneten Bereiche für jede View create/edit austauschen!

Für Create.blade.php
`  <div class="hidden-sm-down">
    
    {{ Form::submit('Speichern', array('class' => 'btn btn-success float-left m-1'))}}
    <input class="btn btn-warning float-left m-1" type="reset" value="Zurücksetzen" />
    <a href="**/images**" class="btn btn-danger float-right m-1" />Abbrechen</a>
  </div>
  <div class="clearfix"></div>
  <div class="hidden-md-up">
    
    {{ Form::submit('Speichern', array('class' => 'btn btn-success m-1 w-100'))}}
    <input class="btn btn-warning m-1 w-100" type="reset" value="Zurücksetzen" />
    <a href="**/images**" class="btn btn-danger m-1 w-100" />Abbrechen</a>
  </div>`

Für edit.blade.php
`  <div class="hidden-sm-down">
    
    {{ Form::submit('Speichern', array('class' => 'btn btn-success float-left m-1'))}}
    <a href="**/images/{{$image->id}}**" class="btn btn-danger float-left m-1" />Abbrechen</a>
    <input type="button" onclick="**$('#dm-delete-image').submit()**" class="btn btn-danger float-right m-1" value="Löschen" />
  </div>
  <div class="clearfix"></div>
  <div class="hidden-md-up">
    
    {{ Form::submit('Speichern', array('class' => 'btn btn-success m-1 w-100'))}}
    <a href="**/images/{{$image->id}}**" class="btn btn-danger w-100 m-1" />Abbrechen</a>
    <input type="button" onclick="**$('#dm-delete-image').submit()**" class="btn btn-danger w-100 m-1" value="Löschen" />
  </div>`

**Comment by Hackyy** [comment]
Erledigt für:
- Information
- Person
- Zitat
- Image
- User
- Austellung

**Comment by Alezyn** [comment]
Erledigt für:

- Texts
- Sources

**Comment by Hansium** [comment]
Für Videos auch erledigt. Mir ist noch aufgefallen, dass der Kommentar  doppelt ist, müsste einmal  heißen :)
